### ISSUE TITLE
Javascript on mobile!

### ISSUE THREAD

**Issue by dkarzon** [akjs/future-meetups#3]
Here is a quick outline of a talk I could do on building mobile apps with the Javascripts. This one is more on techniques than technical stuff but that's people seem to be asking about. Let me know what you think...

---

Let's talk about javascript on mobile devices. Good things, the bad things and the other things.

Why do app over web?

Good?
**Android** - Hurray for CrossWalk! (One WebView to rule them all)
**Windows** - Hurray for Native JS apps! (Javascript is first class)
**iOS** - Hurray for iOS8! (Maybe.)

Bad?
**iOS** - Tools?
**Android** Pre-v4 Android (Is fragmentation still an issue?)
**Windows** - Windows...

Handling platform specifics
- Cordova plugins
- Cordova merges
- JS feature detection

Something about design
- Make the apps look like the platform (Material, Metro, Flat, whatever iOS calls it)
- How do we do this in apps?

Frameworks to look at?
- Ionic

**Comment by jladuval** [comment]
Are you still keen to do a talk on this? It sounds really interesting, I think we should schedule it for an upcoming meetup!

**Comment by dkarzon** [comment]
Yeh, definitely. Just let me know when you want to schedule it.

**Comment by jladuval** [comment]
How much time would you like? Would you prefer it as a 15 or 25 min talk?

**Comment by dkarzon** [comment]
I can do either, 25 minute might be better as there is a fair bit of content to cover. (Unless you want a short version?)

**Comment by jladuval** [comment]
25 is perfect. Will you be available for the October meetup?

**Comment by dkarzon** [comment]
October sounds good to me.

**Comment by frederickfogerty** [comment]
AkJS wouldn't be the place to do a React/React Native talk, would it?
