### ISSUE TITLE
Repeating

### ISSUE THREAD

**Issue by jladuval** [akjs/future-meetups#6]
Can we put a repeating date on the meetup? Something like 'the third Tuesday of every month'. That way we can start fleshing out the future meetups months in advance.

**Comment by wrumsby** [comment]
So, I've scheduled [a meetup](http://www.meetup.com/AucklandJS/events/222525261/) for the 16th of June which would mean "every 3rd Tuesday". I think that works and avoids clashes.

cc @Kevnz, @snikch, @mightymuke, @lindsayjopson, @rapaul

**Comment by jladuval** [comment]
It should be possible to actually set it as repeating on meetup.com though. On http://www.meetup.com/AucklandNodeJs/ we have all of our future meetups shown.

**Comment by wrumsby** [comment]
Ok, I've done that now.

**Comment by jladuval** [comment]
Awesome, thanks.
